### ISSUE TITLE
WynncraftPlayer.getRanking().getPlayer().getSolo().get<someSkill> returns always 0

### ISSUE THREAD

**Issue by DraftedDev** [Bedo9041/jWynn#8]
I dont know why but if I try to get the skill ranking of a player/me it always returns 0.
Here is my code:
`        WynncraftAPI api = new WynncraftAPI();
        WynncraftPlayer player = api.v2().player().stats("MineDrafter").run()[0];
        WynncraftPlayerRanking rank = player.getRanking();
        //Print some skills
        System.out.println(rank.getPlayer().getSolo().getScribing());
        System.out.println(rank.getPlayer().getSolo().getCombat());
        System.out.println(rank.getPlayer().getSolo().getCooking());
        System.out.println(rank.getPlayer().getSolo().getJeweling());
        System.out.println(rank.getPlayer().getSolo().getOverall());`

**Comment by Bedo9041** [comment]
Sorry for the late response. 
I don't believe the API actually returns ranking information for most players, it potentially only gives results if players are in the top rankings, but I haven't done extensive testing.
